### ISSUE TITLE
There is currently no clear documentation or information regarding the supported file types for the edit/preview option in the Storage Blob Container.

### ISSUE THREAD

**Issue by Sagarthore11** [Azure/azure-functions-powershell-worker#1097]
Hello Team,

Greetings!

We recently noticed that in the Azure portal under Storage Account -> Blob Container, we can store files of any type, and this functionality is working as expected. However, when we click on the edit/preview option for files like .docx, .pdf, etc., they do not open. On the other hand, if we download these files and open them locally, they work fine.

It would be helpful to have clear documentation that specifies which file extensions are supported for the edit/preview option in Blob Storage. While this is not a bug, having this documentation would prevent confusion for end users.

Thank you for your help.

**Comment by andystaples** [comment]
@Sagarthore11 why was this issue opened on the Functions PowerShell worker? This issue should be handled by the Azure Portal UX team, you can submit feedback for the Azure Portal using this system inside the portal itself. ![Image](https://github.com/user-attachments/assets/4e562932-e2ba-4e49-a4f0-280abe4ca10a)
Please let us know if we have missed something with this issue that ties back to PowerShell specifically, otherwise we will close this issue in a few days.

**Comment by Sagarthore11** [comment]
Hello @andystaples apologies by mistakenly it tags to PowerShell. Thanks for sharing the details.
