### ISSUE TITLE
Investigate local debugging story for PowerShell Function Apps

### ISSUE THREAD

**Issue by daxian-dbw** [Azure/azure-functions-powershell-worker#120]
This includes func CLI based debugging and VSCode for local Function App development. We can leverage `Enter-PSHostProcess` for this.

**Comment by TylerLeonhardt** [comment]
PowerShell Core shipped but I missed a small piece in the PowerShell extension for vscode. I'll need to ship another version of that.

Also, the F5 scenario (aka running and attaching to a function app by hitting "start debugging") will be difficult because for PowerShell the only way to attach to a process is by knowing the Process ID.

Since this changes every time the worker starts up, this is difficult to know which process to attach to.

Instead, @SteveL-MSFT and I have discussed exposing a way to specify a path to where the named pipe will live so that it's easy to know what to attach to. We'll discuss this more - it'll have to be a change in PowerShell Core.

**Comment by TylerLeonhardt** [comment]
This is done now.
