### ISSUE TITLE
Write-Debug not showing up in App Insights/Console Logs

### ISSUE THREAD

**Issue by toddysm** [Azure/azure-functions-powershell-worker#160]
We are trying to use Write-Debug and Write-Verbose for debug messages but none of the messages appear on the console or in App Insights. The host.json is configured as follows:
```
{
  "version": "2.0",
  "logging": {
    "logLevel": {
      "default": "Trace"
    }
  }
}
```
The following statements:
```
Write-Host "Log levels"
Write-Error "This is an error"
Write-Warning "This is a warning"
Write-Information "This is information"
Write-Verbose "This is verbose"
Write-Debug "This is debug"
```

result in the following logs on the Console and in App Insights:
```
2019-03-08T15:58:42.324 [Information] INFORMATION: Log levels
2019-03-08T15:58:42.717 [Error] ERROR: This is an error

Microsoft.Azure.WebJobs.Script.Rpc.RpcException : Result: ERROR: This is an error
Exception: This is an error
Stack:
2019-03-08T15:58:42.748 [Warning] WARNING: This is a warning
2019-03-08T15:58:42.748 [Information] INFORMATION: This is information
```

Do we need to do anything else as configuration or should this be enough to log the messages?

**Comment by TylerLeonhardt** [comment]
@toddysm can you try something for me?

Can you change your:

```
Write-Verbose "This is verbose"
Write-Debug "This is debug"
```
to 
```
Write-Verbose "This is verbose" -Verbose
Write-Debug "This is debug" -Debug
```
and see if this repros

**Comment by toddysm** [comment]
Yes. This works. It sounds redundant though.

**Comment by TylerLeonhardt** [comment]
Thanks for the feedback! Alternatively you can set your `$VerbosePreference` and `$DebugPreference` for your function executing.

Although it seems redundant, it's actually consistent with `pwsh.exe`. If you don't use `-Verbose` nothing will show up when run interactively.

There's an ongoing discussion in #162 about supporting a log cmdlet called `Write-AzFuncLog` which takes a message and a log level. You would use this instead of `Write-*` (although we wont be removing support for `Write-*`).

Is this something you would be interested in having or would you find yourself using the built-in `Write-*` cmdlets anyway?

We'd love your feedback here or in the mentioned issue!

**Comment by toddysm** [comment]
@TylerLeonhardt My expectation was that if the hosts.json has this setting, then the variables are automatically assumed to be set.

Regarding your question about the AzFuncLog, we prefer to use something that is not Function specific. I assume this will also work on a local machine?

**Comment by daxian-dbw** [comment]
I don't think you want those preference variables to be set automatically by default. Otherwise, a lot relevant verbose messages will be spit out from `Import-Module` and other cmdlets to your trace log.

**Comment by markscholman** [comment]
@daxian-dbw  But if you set them by default, the host.json determines the actual logs that are send to Application Insights. I agree, Trace and Debug logging mode is chatty, but I believe in a debugging scenario that's desired. When setting host.json on error, warning or informational these chatty messages are left out anyway.
