### ISSUE TITLE
Question: Can we already use other triggers like eventgrid?

### ISSUE THREAD

**Issue by bgelens** [Azure/azure-functions-powershell-worker#163]
Curious on how this would look like. With C# you would add additional library, will this be the same with PowerShell? And is it already possible?

**Comment by TylerLeonhardt** [comment]
With C# you get a real EventGrid live object. This is because C# functions run in-process where PowerShell and Python and JavaScript run out of process in a separate worker process... because of this, we don't get those live object...

That said, it does still work! It'll just come in as a property bag hashtable similar to what JavaScript functions get.

**Comment by TylerLeonhardt** [comment]
You still need to install the EventGrid extension to set up the host to receive EventGrid triggers.

**Comment by TylerLeonhardt** [comment]
There's also an EventGrid template available. It's not all that complex as templates go... but it's something to work off of.

**Comment by bgelens** [comment]
Nevermind :) `func new --language=powershell --template="Azure Event Grid trigger"`

**Comment by TylerLeonhardt** [comment]
just so you know, the language here is optional if your Function _APP_ is already a PowerShell Function App.

Also, if you're curious what the available templates are, run:

```
func new
```

and you'll see them all 😄

**Comment by TylerLeonhardt** [comment]
Ok to close this now?

**Comment by bgelens** [comment]
Yes :) Thanks!
