### ISSUE TITLE
Web Cmdlet Socket Exhaustion Concern

### ISSUE THREAD

**Issue by markekraus** [Azure/azure-functions-powershell-worker#174]
One thing we do not handle well in the web cmdlets in PS Core is the singleton nature of HttpClient. HttpClient is intended to be instantiated once and then reused. In PS Core we instantiate a new HttpClient on every call to IWR/IRM. This is somewhat OK for a shell and scripting language, but could be problematic for Functions. A common pattern is to create a azure Function to combine data from multiple endpoints as a single data set. In a high volume environment, the repeated calls to web cmdlets could result in socket exhaustion. [More Info](https://docs.microsoft.com/en-us/aspnet/web-api/overview/advanced/calling-a-web-api-from-a-net-client#create-and-initialize-httpclient)

**Comment by daxian-dbw** [comment]
Back in the days we started to port `Invoke-WebRequest` and `Invoke-RestMethod` to dotnet core, we considered adding a parameter set to those two cmdlet to accept an `HttpClient` to work with, and maybe also a new cmdlet like `New-HttpClient` to help with that. It was the same idea -- to allow the user to reuse the `HttpClient` as she/he sees appropriate. I thought it was a good idea but we didn't get to actually do that ...

I still think it's a good idea that would give users more flexibility and potentially boost perf (a bit?)

**Comment by markekraus** [comment]
I have toyed with the same idea.

One thing that makes that a bit painful is that the HttpClientHandler is where most of the features are applied. They would need to provide us both the HttpClient and HttpClientHandler. At some point, managing that with the existing cmdlets becomes awkward and from a user perspective, maybe more painful than the direct .NET API calls.

Even if we move the web cmdltes to do that, how would we persist the HttpClient and HttpClientHandler singletons between function calls? I have not looked at the runtime in depth, but is each function call a new PowerShell session? Or is it similar to .NET Core runtime where singleton lifecycles are tied to the instance (i.e. a new singleton is instantiated each time the AZ Function boots up or another instance is scaled out)?

**Comment by daxian-dbw** [comment]
A PowerShell session is reused by Azure Function calls, so yes, a singleton is initiated at the function worker boot-up time, and last until the worker is spun down.
But a function worker process may have multiple Runspaces dealing with incoming requests concurrently, so if the web cmdlet is going to carry the singleton, it should have a `ConditionalWeakTable<Runspace, HttpClient>` instead.

**Comment by markekraus** [comment]
I'm not sure I understand that.

The problem is that HttpClientHandler is required for most of the advanced features of the web cmdlets. You can only attach a single HttpClientHandler to an HttpClient singleton. If thread A modifies the HttpClientHandler if can impact HttpClient in thread B and if both modify the HttpClientHandler in both thread A and thread B you get a race condition. Both types are thread safe in that you wont thread lock with any operations performed on either singleton, but the possibility of operations being done in unexpected order on HttpClientHandler is high. For example, Thread A calls `iwr $uriA -SkipCertificateCheck` and thread B calls `iwr $uriB` it possible the call to `$uriB` may have HttpClientHandler.ServerCertificateCustomValidationCallback set to HttpClientHandler.DangerousAcceptAnyServerCertificateValidator and bypass SSL

In C#, the creation of the HttpClientHandler tends to be very static and when the need comes for different endpoints to be handled different, multiple singletons one dedicated to each endpoint are used. This is not something a PowerShell user has been exposed to. Because we expose HttpClientHandler settings as parameter features on the web cmdlets, this implementation flaw is never surfaced to the PS user. We sacrifice good practice and risk socket exhaustion for ease of use.

I read through the docs on ConditionalWeakTable, but I'm not sure how that would address this. Can you elaborate more?

**Comment by daxian-dbw** [comment]
Sorry that I wasn't clear enough with my thoughts.
A singleton instance of `HttpClient` and `HttpClientHandler` won't work because it would cause race conditions when web cmdlets are used in parallel from multiple Runspace, so we need a singleton per Runspace. When the web cmdlet is running, it's easy to find out which Runspace we are running in by `Runspace.Default` (or other ways through `PSCmdlet`), then we can query the `ConditionalWeakTable` to see if we already have a `HttpClient` allocated for that Runspace. If yes, then use the existing one; if no, then create a new one and cache it in the table. In this way, it's guaranteed that different `HttpClient` are used in different Runspaces and also within a Runspace, the same `HttpClient` instance is reused throughout the Runspace's lifetime.

I'm not that familiar with the relationship between `HttpClient` and `HttpClientHandler`. I'm assuming that `HttpClient` holds a reference to `HttpClientHandler` which the web cmdlets can update based on the endpoint requirement before sending the request. I may be wrong. But the idea is that, we need to have one singleton per Runspace, so that no race conditions when running web cmdlets from multiple Runspaces concurrently.

**Comment by markekraus** [comment]
Ah that's clear, thanks. It's certainly better than one per call to iwr/irm. This is a model I had considered before with a different type. I was also considering a lazy<t> for it to instantiate on demand.

**Comment by joeyaiello** [comment]
@daxian-dbw to open an issue in PowerShell/PowerShell and close this one

**Comment by Francisco-Gamino** [comment]
I've opened an issue in the PowerShell repo. Please see https://github.com/PowerShell/PowerShell/issues/9977.
