### ISSUE TITLE
PnP references in Powershell Azure function 2.0

### ISSUE THREAD

**Issue by antoniobriones** [Azure/azure-functions-powershell-worker#211]
Hi, 

How should I include references to SharePointPnPPowerShellOnline in 2.0 function? I read posts (for 1.0) that say about saving the module locally and then uploading it to the modules folder, but I don't see such folder in 2.0.

Thanks

**Comment by TylerLeonhardt** [comment]
My understanding is that the PnP module does not work with PowerShell Core. Can you confirm that this module works with PowerShell Core 6.2 in a normal powershell console?

Here are the docs you are looking for:
https://docs.microsoft.com/en-us/azure/azure-functions/functions-reference-powershell#function-app-level-modules-folder

If a folder isn't there, you need to create it.

**Comment by antoniobriones** [comment]
Thanks,@TylerLeonhardt, that did it, i was placing the Modules folder in an incorrect place, wwwroot is set as envpath so it needs to go in there.

Anyway, all PnP cmdlets now fail and the cause is that they don't run in Powershell core 6.2. Do you or anyone know if there will be support for it in the future? Or will Azure Functions 2.0 support normal Powershell? What's the approach that we should follow now? Use a 1.0 function?

**Comment by TylerLeonhardt** [comment]
Yeah. I guess that's the work around for now. We were talking about this on Twitter the other day:

https://twitter.com/erwinvanhunen/status/1123644857094934530?s=19

It sounds like they're working on it.

**Comment by JustinGrote** [comment]
@antoniobriones So this is probably 
### SUPER UNSUPPORTED 

but the current 2.0 worker in Azure still runs on Windows, and the 5.1 powershell.exe is still there. I tried using the wincompatibility module but as expected none of the WINRM remoting infrastructure that it requires works, so your other option is to put the logic or whatever you want to do with sharepoint into a separate script, export the results to CLIXML somewhere for temp, and then re-import them into your powershell core session.

Not the prettiest solution and definitely not the most performant, but it's a workaround for now if you absolutely need it.

**Comment by TylerLeonhardt** [comment]
Actually yes. @JustinGrote is right and that's actually probably a more supported solution than using v1.

**Comment by antoniobriones** [comment]
Thanks guys. Is there any chance that this approach you're suggesting may become unsupported for some reason? Like.. the worker stopping from running on Windows or anything like that? The solution we're preparing is for SP Site Provisioning and my company provisions around 100 sites per day, we couldn't be supporting an outage here.

**Comment by JustinGrote** [comment]
Unsupported in that if you call MS support they won't have a clue what you
are doing probably, but it will "work"

Only reason I can think of is if the worker switches to Linux OS, but I'm
sure there'd be plenty of notice and a compatibility option for that.

**Comment by JustinGrote** [comment]
Also if you're that concerned about support you should use azure automation
instead for a more clear roadmap at this point.

**Comment by antoniobriones** [comment]
@JustinGrote, i'm just trying to apply a pnp provisioning template after a site gets provisioned. For that, I'm calling a flow from the site design and that flow is calling the function. So you suggest replacing the function by a runbook and making a http request to it from the flow?

**Comment by JustinGrote** [comment]
This is my non-Microsoft-employee-opinion, but if you are planning this for long term production support, it should run on a GA platform, and the only options in that regard at the moment are Azure Automation or a virtual machine.

That being said, in our company run production code that processes 15k tickets a week on the "experimental" azure functions 1.x powershell runtime and have experienced no issues, but we were willing to accept the risks associated with that, and are able to self-support in the event of issues and have a failover plan to a VM if required :). So far my experience is that 2.x is just as stable so far and Application Insights makes it far better for our purposes than Azure Automation (or any other platform), just keep in mind you are developing on a **public preview** platform, and going off the reservation by calling the embedded powershell.exe rather than using Powershell Core.

Will it work? Sure, we do stuff like that all the time. Is anything around this likely to change before GA? Seeing as the Linux is still preview for more "common" function languages, probably not. But you need to ask yourself:

1. Does this code need to live for 5 years? If so, better to wait until PnP is supported in Powershell COre.

1. Is the next guy coming after you who has to support your code going to be able to understand/support it, and be able to get support if he can't? You'll need to develop your own safety net around that.

If I were you, I'd go ahead and do it as a stop-gap, with a plan to migrate to the core version of PnPOnline once it becomes available. As long as you set your stakeholder expectations appropriately, then you should be fine.

**Comment by antoniobriones** [comment]
Thanks @JustinGrote for taking the time! I'll go with 2.0 functions calling Powershell.exe for the time being.

**Comment by joeyaiello** [comment]
Resolving as answered. Thanks for all the help, @JustinGrote!
