### ISSUE TITLE
Different behavior between local execution and published execution for an HTTP input binding ($HttpRequest.body)

### ISSUE THREAD

**Issue by ahmadabdalla** [Azure/azure-functions-powershell-worker#228]
On the V2 Functions, we're experiencing different behavior when looking into the body of an HTTP input binding:

I’m sending the following BODY: (@{OperationType='ScaleIn';OperationId='Test11'} | ConvertTo-Json)

param
(
    $HttpRequest,
    $TriggerMetadata
)

_$HttpRequest.body_ gives the following output:
--------------------------------------------------------

**LOCAL EXECUTION**
[20/05/2019 12:45:04 AM] OUTPUT: {
[20/05/2019 12:45:04 AM]   "OperationType": "ScaleIn",
[20/05/2019 12:45:04 AM]   "OperationId": "Test11"
[20/05/2019 12:45:04 AM] }

---------------------------------------------------------
**PUBLISHED EXECUTION**
2019-05-20T00:39:18.834 [Information] OUTPUT: Name                           Value
2019-05-20T00:39:18.834 [Information] OUTPUT: ----                           -----
2019-05-20T00:39:18.834 [Information] OUTPUT: OperationType                  ScaleIn
2019-05-20T00:39:18.835 [Information] OUTPUT: OperationId                    Test11

----------------------------------------------------------

Is this normal? 

@darrenjrobinson

**Comment by AnatoliB** [comment]
Thank you for reporting this. I can repro the issue and it does not look normal to me. When executed on Azure, the Body property contains a hashtable with values parsed out of the JSON payload. When executed locally, the same property contains the original JSON string.

While I'm investigating this, the following workaround seems to work: if you specify `application/json` in the `content-type` header, you will get the consistent behavior in both cases (matching the behavior in Azure).

**Comment by AnatoliB** [comment]
The behavior of the published execution is intentional, and the local behavior you are observing is a bug. This issue has been fixed in [azure-functions-powershell-worker v0.1.102-preview](https://github.com/Azure/azure-functions-powershell-worker/releases/tag/v0.1.102-preview). This version is already deployed to Azure, but the latest release of azure-function-core-tools ([2.7.1158](https://github.com/Azure/azure-functions-core-tools/releases/tag/2.7.1158)) refers to [azure-functions-powershell-worker v0.1.95](https://github.com/Azure/azure-functions-powershell-worker/releases/tag/v0.1.95). The next release of azure-function-core-tools should have this fix included.
