### ISSUE TITLE
Concurrent Connections

### ISSUE THREAD

**Issue by npachal** [Azure/azure-functions-powershell-worker#264]
This might be expected behaviour. I've created a logic app which runs the following every ten minutes:

`{
    "definition": {
        "$schema": "https://schema.management.azure.com/providers/Microsoft.Logic/schemas/2016-06-01/workflowdefinition.json#",
        "actions": {
            "HTTP": {
                "inputs": {
                    "body": {
                        "warmup": true
                    },
                    "method": "POST",
                    "uri": "https://pachal-survey.azurewebsites.net/api/SubmitGeo"
                },
                "runAfter": {},
                "type": "Http"
            },
            "HTTP_2": {
                "inputs": {
                    "body": {
                        "warmup": true
                    },
                    "method": "POST",
                    "uri": "https://pachal-survey.azurewebsites.net/api/SubmitGeo"
                },
                "runAfter": {},
                "type": "Http"
            },
            "HTTP_3": {
                "inputs": {
                    "body": {
                        "warmup": true
                    },
                    "method": "POST",
                    "uri": "https://pachal-survey.azurewebsites.net/api/SubmitGeo"
                },
                "runAfter": {},
                "type": "Http"
            }
        },
        "contentVersion": "1.0.0.0",
        "outputs": {},
        "parameters": {},
        "triggers": {
            "Recurrence": {
                "recurrence": {
                    "frequency": "Minute",
                    "interval": 10
                },
                "type": "Recurrence"
            }
        }
    }
}`

What is notice is that one of the three invocations has a 3 second response time, and the remaining two have 30 second response times from the PowerShell function. I've been running this test for the past two days. If a PowerShell function on a consumption plan has more than one concurrent connection is it suppose to cause a cold startup for each concurrent request?

**Comment by eamonoreilly** [comment]
You can set the concurrency of the function app by following the documentation on https://docs.microsoft.com/en-us/azure/azure-functions/functions-reference-powershell#concurrency 

You could create the app setting PSWorkerInProcConcurrencyUpperBound and perhaps set this to 10.

Thanks,
Eamon

**Comment by npachal** [comment]
Thanks for the note. I did do that as follows:
![snip](https://user-images.githubusercontent.com/24705984/60198902-8bd1a780-97f7-11e9-9a01-1a2f05824d7e.PNG)

Not to turn this into troubleshooting my code, but the first request will happen in once 1 second, than the subsequent requests 2..n will all complete after 40 seconds. I'm wondering what is happening behind the scenes with resource provisioning.

**Comment by TylerLeonhardt** [comment]
The Azure Functions sandbox in the Consuption Plan only has 1 CPU core. WIth concurrency turned on, you will be able to process messages concurrently... but since the handlers of those messages are sharing 1 core, you have decreased performance because of context switching between threads.

@eamonoreilly will have to take this to the Functions team about how to help out with this but Consumption has this limitation... You'd have to move to the dedicated plan or premium plan to allow for multiple cores.

**Comment by AnatoliB** [comment]
Please note though that PowerShell workloads are rarely CPU-bound, so the number of CPU _cores_ usually does not matter that much. What actually matters is the number of _threads_/_runspaces_, and this is what `PSWorkerInProcConcurrencyUpperBound` is helping with (to some extent). When this limit is reached, getting more concurrency requires spawning more workers, and this story is not very transparent in Consumption...

**Comment by TylerLeonhardt** [comment]
@AnatoliB just to clarify, I wasn't speaking about PowerShell workflows (as in PowerShell actually executing). 

I was speaking about the PowerShell worker process all up. That process's performance, which has the ability to spin up multiple threads/runspaces, will be worse if it does due to the single logical core having to context switch between threads.

That is to say, to get the fastest performance, it's best to keep `PSWorkerInProcConcurrencyUpperBound` at 1 because you don't have any context switching between threads. Increasing the concurrency, to 10, for example, means that worst case the single core will be shared between 10 active threads... pushing the can down the road until they all are finished.

The same would happen in a C# worker (if such a thing existed and it supported concurrency) because it would also be bounded by the single core being able to context switch fast enough.

Increase the number of cores, and you'll see better results but that can't be done in Consumption today.

**Comment by JustinGrote** [comment]
Just like to note on this thread that this is an excellent use for queues
in fan out situations. Just throw all your requests in a queue and have a
queue trigger function. The worker will then gradually spin up more
instances to handle the queue and each will have a dedicated core per
processor. Parallel execution without the fuss.

**Comment by npachal** [comment]
Is there a way to tell what will cause another function system to be provisioned as opposed to just using the additional run space on the same system (if concurrency is set more than 1)?

**Comment by eamonoreilly** [comment]
Scaling of new hosts is determined by the trigger type. For http, as requests come in that cause load on a host, additional hosts are created to meet the load. For triggers like queues, service bus, etc, the scale controller looks for request build up and scales new hosts as needed.
Closing this issue as the concurrency behavior is documented in https://docs.microsoft.com/en-us/azure/azure-functions/functions-reference-powershell#concurrency

**Comment by ghclo** [comment]
> @AnatoliB just to clarify, I wasn't speaking about PowerShell workflows (as in PowerShell actually executing).
> 
> I was speaking about the PowerShell worker process all up. That process's performance, which has the ability to spin up multiple threads/runspaces, will be worse if it does due to the single logical core having to context switch between threads.
> 
> That is to say, to get the fastest performance, it's best to keep `PSWorkerInProcConcurrencyUpperBound` at 1 because you don't have "any" context switching between threads. Increasing the concurrency, to 10, for example, means that worst case the single core will be shared between 10 active threads... slowly pushing each of the cans (threads) down the road until they all are finished.
> 
> The same would happen in a C# worker (if such a thing existed and it supported concurrency) because it would also be bounded by the single core being able to context switch fast enough.
> 
> Increase the number of cores, and you'll see better results but that can't be done in Consumption today.

Even `PSWorkerInProcConcurrencyUpperBound` is set to 10, my understanding is that there will be up to 10 runspaces/threads (in each worker process, specified by `FUNCTIONS_WORKER_PROCESS_COUNT`) sharing the same context of each worker process, so no performance decreased causing by context switching.

Please correct me if I am wrong.

**Comment by JustinGrote** [comment]
@ghclo He is referring to low-level CPU context switching, which is the CPU switching from working on one thing to working on another. 

CPU's (for the most part) can't do things in parallel in a single core, and each powershell worker is a single core instance. If concurrency is 10, picture a 10-lane highway that plenty of cars can drive but all the roads merge to a single lane for a toll booth. You have a traffic jam at that point because only one car at a time can go through, then it opens back up to 10 lanes.

The 10 lane highway is the concurrent powershell processes, the 1 lane toll booth is the CPU :)

The solution is to write your solutions in a way that provision enough workers to handle the load. For instance, you can use the Durable functions pattern, or simply connect your functions together with Queue Input and Output bindings. When the queue backs up, Azure functions will automatically add more workers (toll booths) to handle the traffic.

**Comment by AnatoliB** [comment]
@ghclo Please note, however, that the CPU context switching overhead may or may not be noticeable depending on what your function code does. Within the 10-lane highway analogy, a single toll booth will not create any traffic jam if the distance between cars on each lane is large enough. This is exactly what happens with I/O-bound workloads, which are quite typical for PowerShell.

For example, if your function restarts an Azure VM and you need to execute it for 100 VMs as soon as possible, each execution will take a few seconds consuming very little CPU, and CPU context switching will not be your most important concern. On the contrary, if you try to match the number of threads to the number of cores, you will end up either spending time on executing everything sequentially, or spending money on many underutilized worker instances. In this situation, increasing `PSWorkerInProcConcurrencyUpperBound` or `FUNCTIONS_WORKER_PROCESS_COUNT` will increase the throughput on this specific workload almost proportionally without a costly scale-out. By _deoptimizing locally_ (allowing some CPU context switching), you actually _optimize globally_.

CPU-bound workloads are different. If your functions are busy performing heavy computations, CPU context switching will matter. But both "CPU-bound" and "I/O-bound" are just simplified abstractions. In reality, you have to deal with a mix unique to your specific workload, so you want to experiment with the settings and find what works for you.
