### ISSUE TITLE
Issue with exporting certificate from key vault

### ISSUE THREAD

**Issue by januschr** [Azure/azure-functions-powershell-worker#273]
Hello,

I am trying to export a certificate from a key vault in a powershell function app using this code:
```powershell
$cert = Get-AzKeyVaultSecret -VaultName $KeyVaultName -Name $CertificateName
$certPassword = (Get-AzKeyVaultSecret -VaultName $KeyVaultName -Name $CertificatePasswordSecret).SecretValueText
$certSecretBytes = [System.Convert]::FromBase64String($cert.SecretValueText)
$certCollection = New-Object System.Security.Cryptography.X509Certificates.X509Certificate2Collection
$certCollection.Import($certSecretBytes, $null, [System.Security.Cryptography.X509Certificates.X509KeyStorageFlags]::Exportable)
$protectedCertificateBytes = ($certCollection.Export([System.Security.Cryptography.X509Certificates.X509ContentType]::Pkcs12, $certPassword)
```

This code works if I run it in a powershell locally, but when running in the function app it throws this error:

```
ERROR: Exception calling "Import" with "3" argument(s): "The system cannot find the file specified" Microsoft.Azure.WebJobs.Script.Rpc.RpcException : Result: ERROR: Exception calling "Import" with "3" argument(s): "The system cannot find the file specified"
Exception: Exception calling "Import" with "3" argument(s): "The system cannot find the file specified"
Stack: at System.Management.Automation.ExceptionHandlingOps.ConvertToMethodInvocationException(Exception exception, Type typeToThrow, String methodName, Int32 numArgs, MemberInfo memberInfo)
    at CallSite.Target(Closure , CallSite , Object , Object , Object , X509KeyStorageFlags )
    at System.Management.Automation.Interpreter.DynamicInstruction`5.Run(InterpretedFrame frame)
    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame) 
```

It seems to expect that `$certSecretBytes` is a file in the `$certCollection.Import()` call? 

Is there a work around for this?

**Comment by anirudhgarg** [comment]
Can you please try this: 
https://github.com/projectkudu/kudu/wiki/Configurable-settings#add-user-profile-support-for-a-site

The system cannot find the file specified issue with X509Certificate2
If you new up X509Certificate2 instance from a pfx file or cert encoded containing private key, you may run into CryptographicException: The system cannot find the file specified.. The reason is Windows stores private key as a file under a user profile directory. By default, Azure Web App (AppService) does not load user profile (avoid overhead for majority scenarios where it is not needed). Hence, the The system cannot find the file specified. issue. To work around, set the below appSetting to enable User Profile.

WEBSITE_LOAD_USER_PROFILE=1

**Comment by januschr** [comment]
Thank you! That solved the issue.

**Comment by jorgefdezsa-zz** [comment]
Thank you, Me too
