### ISSUE TITLE
Powershell shell missing in the container mcr.microsoft.com/azure-functions/powershell:2.0

### ISSUE THREAD

**Issue by alwaysharsha** [Azure/azure-functions-powershell-worker#357]
#### Question
In the docker image **mcr.microsoft.com/azure-functions/powershell:2.0** There is no powershell pre-installed due to which the powershell scripts aren't running.

CMD > **docker run -it mcr.microsoft.com/azure-functions/powershell:2.0  pwsh**
C:\Program Files\Docker\Docker\Resources\bin\docker.exe: Error response from daemon: OCI runtime create failed: container_linux.go:345: starting container process caused "exec: \"pwsh\": executable file not found in $PATH": unknown.

When i execute with bash, i could get into the container and verified that powershell is missing. Due to which powershell scripts aren't running.

Doesn't this image should pre contain the powershell ?

**Comment by AnatoliB** [comment]
@alwaysharsha This image contains the PowerShell worker for Azure Functions. In order to execute PowerShell code, the worker uses PowerShell SDK directly, so there is no need to invoke pwsh.exe or have it installed on the image just for the purposes of running PowerShell functions. I realize that there are scenarios where invoking pwsh.exe from PowerShell functions is also desirable, so we _may_ want to include pwsh.exe just in case. But please let us know why you expect that. This does not look like a mainstream scenario, so you may need to create your own custom image with pwsh.exe instead (we can help).

**Comment by alwaysharsha** [comment]
I have downloaded a Powershell module from Powershell gallery and placed in modules folder.

In the run.ps1 i am just referencing the cmdlet to set the Bitbucket server url
https://github.com/i9shankar/ps-bitbucket/#set-server-url
> Set-BitBucketServer -Url "https://company.domain.net"

When i build the docker image and execute its unable to identify the module and load, see the error message mentioned below.

If the same i execute outside the docker using *func host start* it works perfectly fine. 


```
info: Function.listBranches[0]
      Executing 'Functions.listBranches' (Reason='This function was programmatically called via the host APIs.', Id=bc7777d4-58a1-4413-83f5-977399358290)
dbug: Microsoft.Azure.WebJobs.Script.Description.WorkerLanguageInvoker[0]
      Sending invocation id:bc7777d4-58a1-4413-83f5-977399358290
dbug: Microsoft.Azure.WebJobs.Script.Rpc.FunctionDispatcher[0]
      Posting invocation id:bc7777d4-58a1-4413-83f5-977399358290 on workerId:a2a5bd33-aee1-4a82-a96a-b8729b24c69e
info: Function.listBranches.User[0]
      INFORMATION: PowerShell HTTP trigger function processed a request.
fail: Function.listBranches.User[0]
      ERROR: Set-BitBucketServer : The term 'Set-BitBucketServer' is not recognized as the name of a cmdlet, function, script file, or operable program.
      Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
      At /home/site/wwwroot/listBranches/run.ps1:27 char:5
      +     Set-BitBucketServer -Url "https://company.domain.net"
      +     ~~~~~~~~~~~~~~~~~~~
      + CategoryInfo          : ObjectNotFound: (Set-BitBucketServer:String) [], CommandNotFoundException
      + FullyQualifiedErrorId : CommandNotFoundException

      Script stack trace:
         at <ScriptBlock>, /home/site/wwwroot/listBranches/run.ps1: line 27

      System.Management.Automation.CommandNotFoundException: The term 'Set-BitBucketServer' is not recognized as the name of a cmdlet, function, script file, or operable program.
      Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
         at System.Management.Automation.CommandDiscovery.LookupCommandInfo(String commandName, CommandTypes commandTypes, SearchResolutionOptions searchResolutionOptions, CommandOrigin commandOrigin, ExecutionContext context)
         at System.Management.Automation.CommandDiscovery.LookupCommandInfo(String commandName, CommandOrigin commandOrigin, ExecutionContext context)
         at System.Management.Automation.CommandDiscovery.LookupCommandInfo(String commandName, CommandOrigin commandOrigin)
         at System.Management.Automation.CommandDiscovery.LookupCommandProcessor(String commandName, CommandOrigin commandOrigin, Nullable`1 useLocalScope)
         at System.Management.Automation.ExecutionContext.CreateCommand(String command, Boolean dotSource)
         at System.Management.Automation.PipelineOps.AddCommand(PipelineProcessor pipe, CommandParameterInternal[] commandElements, CommandBaseAst commandBaseAst, CommandRedirection[] redirections, ExecutionContext context)
         at System.Management.Automation.PipelineOps.InvokePipeline(Object input, Boolean ignoreInput, CommandParameterInternal[][] pipeElements, CommandBaseAst[] pipeElementAsts, CommandRedirection[][] commandRedirections, FunctionContext funcContext)
         at System.Management.Automation.Interpreter.ActionCallInstruction`6.Run(InterpretedFrame frame)
         at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)


```

To validate this i was trying to run the powershell module manually inside the docker and realized that it doesn't have pwsh.

Can you let me know how to load the powershell modules correctly in this docker image.

**Comment by AnatoliB** [comment]
This error message is normally caused by one of these reasons:

- the module is not on PSModulePath, so PowerShell cannot find it (you can check this by tracing the `$env:PSModulePath` value at the beginning of your function, it normally contains something like `/home/site/wwwroot/Modules:/azure-functions-host/workers/powershell/Modules`, and then either adjust your module location on the container accordingly or invoke `Import-Module` with the full module path); **or**
- the module is found, but PowerShell failed to autoload it (in order to diagnose that, invoke `Import-Module` from your function explicitly and check the errors).

If you still have reasons to diagnose this by running pwsh.exe on the container, you can install it into your own container by following these [instructions](https://docs.microsoft.com/en-us/powershell/scripting/install/installing-powershell-core-on-linux?view=powershell-6).
