### ISSUE TITLE
Exception thrown with Push-OutputBinding

### ISSUE THREAD

**Issue by plmcgrn** [Azure/azure-functions-powershell-worker#455]
I've been using non-HTTP bindings for the PowerShell worker for a while.  I recently created a new Function app that uses HTTP input and output bindings.  While the input binding does work, the output binding seems a bit dodgy.

If I define the binding as a "fake" name not defined in function.json, my worker will process as expected.  However, if I define the binding as the same name defined in function.json, it fails with an internal stack trace and the code preceding the call to Push-OutputBinding is never fired.

Here's the function.json
```
{
  "bindings": [
    {
      "authLevel": "anonymous",
      "type": "httpTrigger",
      "direction": "in",
      "name": "Request",
      "methods": [
        "post"
      ]
    },
    {
      "type": "http",
      "direction": "out",
      "name": "Response"
    }
  ]
}
```
Note the only real change I've made from the default template is removing the GET method, as I only want HTTP POSTS hitting this trigger.

When I call this
```
    Push-OutputBinding -Name res -Value ([HttpResponseContext]@{
            StatusCode = [System.Net.HttpStatusCode]::OK
        })
```
The function doesn't fail hard.  Note the "res" named value, instead of "Response" as defined in function.json.  It only complains about the unresolved name.

```
Exception: System.InvalidOperationException: The specified name 'res' cannot be resolved to a valid output binding of this function.
   at System.Management.Automation.MshCommandRuntime.ThrowTerminatingError(ErrorRecord errorRecord)
```

However, when I define the Push-OutputBinding per the template that Visual Studio Code generates, and the binding name matches the output binding name in function.json, it fails hard.

```
    Push-OutputBinding -Name Response -Value ([HttpResponseContext]@{
            StatusCode = [System.Net.HttpStatusCode]::OK
        })

Exception: Object reference not set to an instance of an object.
Stack:    at Microsoft.Azure.Functions.PowerShellWorker.Utility.TypeExtensions.DeriveContentType(HttpResponseContext httpResponseContext, RpcHttp rpcHttp) in C:\projects\azure-functions-powershell-worker\src\Utility\TypeExtensions.cs:line 196
   at Microsoft.Azure.Functions.PowerShellWorker.Utility.TypeExtensions.ToRpcHttp(HttpResponseContext httpResponseContext) in C:\projects\azure-functions-powershell-worker\src\Utility\TypeExtensions.cs:line 188
   at Microsoft.Azure.Functions.PowerShellWorker.Utility.TypeExtensions.ToTypedData(Object value) in C:\projects\azure-functions-powershell-worker\src\Utility\TypeExtensions.cs:line 242
   at Microsoft.Azure.Functions.PowerShellWorker.RequestProcessor.BindOutputFromResult(InvocationResponse response, AzFunctionInfo functionInfo, Hashtable results) in C:\projects\azure-functions-powershell-worker\src\RequestProcessor.cs:line 465
   at Microsoft.Azure.Functions.PowerShellWorker.RequestProcessor.ProcessInvocationRequestImpl(StreamingMessage request, AzFunctionInfo functionInfo, PowerShellManager psManager, FunctionInvocationPerformanceStopwatch stopwatch) in C:\projects\azure-functions-powershell-worker\src\RequestProcessor.cs:line 305
```
In this latter case, the code preceding the Push-OutputBinding doesn't even fire, from what I can tell in the logs.  I'm not calling this more than once, however, I do have the entire process wrapped in a try...catch, if that matters.

**Comment by AnatoliB** [comment]
@plmcgrn First of all, you seem to be hitting #269. The issue is fixed in the code, but this has not been deployed to Azure yet (expect this to happen within the next 2-4 weeks). In the meantime, the workaround is to initialize the `Body` property of the object passed to `Push-OutputBinding` with anything but `$null`: see https://github.com/Azure/azure-functions-powershell-worker/issues/269#issuecomment-510226401.

Regarding the wrong binding name: by design, `Push-OutputBinding` should throw an exception when a wrong binding name is provided. The exception you are observing is expected. However, you also have an opportunity to catch this exception in the function script, and perhaps this is exactly what happens:

> I do have the entire process wrapped in a try...catch

If you catch an don't re-throw this exception, the function will complete.

Also, if `Push-OutputBinding` throws an exception, I would not expect this:

> the code preceding the call to Push-OutputBinding is never fired

The PowerShell worker does not change the execution order of commands in the function script, and does not look up all the values passed to `Push-OutputBinding` in advance. It just executes the code according to PowerShell rules. If `Push-OutputBinding` had a chance to validate the binding name and throw an exception, this means the execution flow led to the `Push-OutputBinding` invocation. If you share your code, this may help.

**Comment by plmcgrn** [comment]
@AnatoliB thank you for the quick response and pointer to the workaround. Confirmed that setting Body to an empty string instead of $null is a valid workaround for me, as well.  Setting the binding name to the one noted in function.json now succeeds, and instead of failing, I'm able to respond with the desired HTTP 200 OK.  Now that I know this works, I can build more robust error handling in my trigger code to pass non-200 codes back for business logic failure conditions.

```
    Push-OutputBinding -Name Response -Value ([HttpResponseContext]@{
            StatusCode = [System.Net.HttpStatusCode]::OK
            Body       = ""
        })
```
