### ISSUE TITLE
$error not equal $null by default

### ISSUE THREAD

**Issue by SCOMnewbie** [Azure/azure-functions-powershell-worker#470]
Hi,

It seems that (even for a prestine function) $error variable does not equal $null. 

If you want to reproduce this, you simply have to create a new HTTP Powershell function through the portal and add where you want: 

``` Powershell
Write-host "Error count is: $($error.count)"
Write-Host $Error
```
You will see that $error contains the error:
"Could not load file or assembly 'System.Threading.Tasks.Extensions, Version=4.3.1.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'."

Is it a normal behavior? Is my only option is using a plaster like $error.clear() on top of my script?

Cheers,
François

**Comment by AnatoliB** [comment]
#242 seems to be the root cause. Invoking `$error.clear()` is a good workaround.

In general, it is a good idea to avoid any assumptions on whether you get a brand new PowerShell session or not. In order to improve function start time, we need to reuse PowerShell sessions, at least by default, which may carry over some state. We should be able to clear `$error` automatically to address this specific problem, but it is unlikely that we will resolve #242 soon (and, even if we do, it will be "opt-in" as it will hurt performance).
