### ISSUE TITLE
Durable Function activity failures are difficult to handle

### ISSUE THREAD

**Issue by AnatoliB** [Azure/azure-functions-powershell-worker#572]
When an activity function fails because of an exception, this exception is not propagated to the orchestrator function. For example, the `Invoke-ActivityFunction` call below will not throw any exception, will not write anything to the Error stream, the orchestration function will continue execution, and the orchestration will reach the 'Completed' status.

**Activity function (MyActivity):**
``` PowerShell
throw 'Something is wrong'
```

**Orchestrator function:**
``` PowerShell
Invoke-ActivityFunction -FunctionName 'MyActivity'
...
```
As a result, there is no clean and simple way to handle failures. It is technically possible to check the activity function logs (as the exception will be reported there), or use other means to check for other side effects to understand whether the activity succeeded or not. However, these solutions are complicated and should be invented on the case-by-case basis. Instead, we should make `Invoke-ActivityFunction` report regular PowerShell errors and let the orchestrator function use regular PowerShell language constructs to handle these errors.

**Comment by cgillum** [comment]
I created a new PowerShell app using [this quickstart](https://docs.microsoft.com/en-us/azure/azure-functions/durable/quickstart-powershell-vscode), modified the activity function to throw an exception, and I'm observing the behavior described in this issue: activity failures are not propagated to the orchestrator function. An error is recorded in the activity function logs, but the activity function returns a null output instead of throwing an exception.

```
Azure Functions Core Tools
Core Tools Version:       4.0.4590 Commit hash: N/A  (64-bit)
Function Runtime Version: 4.5.2.18383
```

We have an active ICM for this as well (314264370). I'm not sure whether this is a regression. Reactivating.

FYI @davidmrdavid

**Comment by cgillum** [comment]
I have since learned that you have to explicitly enable exception propagation for cmdlets in PowerShell in order for things like try/catch to work properly. This was not documented in our error handling documentation for PowerShell, so I submitted a PR to add this critical information: https://github.com/MicrosoftDocs/azure-docs-pr/pull/203648.

Once published, the updated guidance can be found here: https://docs.microsoft.com/azure/azure-functions/durable/durable-functions-error-handling?tabs=powershell#errors-in-activity-functions
