### ISSUE TITLE
Unable to install module in a PowerShell project. 

### ISSUE THREAD

**Issue by derhallim** [Azure/azure-functions-powershell-worker#595]
### Expected behavior
> Adding a module name in requirements.psd1 and running the function, should install this module.

### Actual behavior
> I have the following content in my requirements.psd1: 
```
# This file enables modules to be automatically managed by the Functions service.
# See https://aka.ms/functionsmanageddependency for additional information.
#
@{
    'Az' = '5.*'; 
    'PnP.PowerShell' = '1.2.13-nightly';
}

```

I am using VSCode with PowerShell. This is the content of host.json: 

```
{
  "version": "2.0",
  "logging": {
    "applicationInsights": {
      "samplingSettings": {
        "isEnabled": true,
        "excludedTypes": "Request"
      }
    }
  },
  "extensionBundle": {
    "id": "Microsoft.Azure.Functions.ExtensionBundle",
    "version": "[2.*, 3.0.0)"
  },
  "managedDependency": {
    "enabled": true
  }
}
```
I am still doing the development locally, but using Azure for the storage. Is there something else that needs to be done? Does the requirements.psd1 only works when the function is pushed to the cloud?

**Comment by AnatoliB** [comment]
@derhallim Installing modules via requirements.psd1 works both locally and in the cloud. Your code looks correct.

What makes you think the module is not installed? Does you function app fail? Do you have any logs?

Your code looks correct, but please keep in mind:

- The modules are installed to a special location that is automatically made available to the function app when it runs. These modules are _not_ installed in the machine or user scope, so if you run `Get-Module` from a stand-alone PowerShell session, you well not see these modules. This is intentional.
- When you start an app for the first time after editing requirements.psd1, function invocations are blocked until the initial download of modules is complete. Depending on your network connection and the PS Gallery performance, it can take 1-2 minutes or longer. When this happens, you get a warning in the logs explaining that.

If this still does not work for you, please collect and share the logs.
