### ISSUE TITLE
No Record of unhandled failure in AZ function Monitor UI

### ISSUE THREAD

**Issue by v-anvari** [Azure/azure-functions-powershell-worker#687]
This is regarding an issue logged in Functions-Host. https://github.com/Azure/Azure-Functions/issues/1939

We wanted to understand if there is an exception while using the Powershell worker that is not logging the unhandled exception in the Monitor Tab in the Azure portal, but, the logs are logged failure in App insight logs. We don't see this behavior while using C#.

**Comment by Francisco-Gamino** [comment]
Hello @v-anvari -- Could you please provide the repro steps, expected behavior and actual behavior? Thanks.

**Comment by v-anvari** [comment]
Hi @Francisco-Gamino , A sample code using powershell is provided here -https://github.com/Azure/Azure-Functions/issues/1939#issuecomment-887874742. 

Repro steps:
Any trigger trying to get an unhandled exception in the code. 

Expected behavior:
1. These unhandled exception should report as failure in the monitor tab in the Azure functions (portal)

Actual behavior:
1. The unhandled exception doesn't report as a failure or success in the monitor tab, but it logs as a failure in the application insights

I tried to repro using c#, but , it logs as failure in both the places. May be the issue is with how powershell worker reads these exceptions.

**Comment by AnatoliB** [comment]
@v-anvari Could you please provide more details on the unhandled exception: what is this exception, how do you observe it, what makes you think there is actually an unhandled exception (and not just the function timing out)?

I tried to run the code from https://github.com/Azure/Azure-Functions/issues/1939#issuecomment-887874742, and I do see it timing out (most likely because of the very high serialization depth limit). The timeout is reported properly in the Monitor tab:
![image](https://user-images.githubusercontent.com/11563624/135507419-aafb3e29-051f-43ff-9ce9-be77cbc830fa.png)

**Comment by v-anvari** [comment]
Thank you @AnatoliB , Thank you for the details, I wasn't able to repro using powershell. 
Tagging @chughesvf for further details as this issue is user specific
