### ISSUE TITLE
Add FunctionApp "modules path" to PSModulePath

### ISSUE THREAD

**Issue by tylerl0706** [Azure/azure-functions-powershell-worker#76]
We need to do the work that will add the FunctionApp's "modules path" to the `PSModulePath` so that we enable a way for users to leverage modules in their functions.

The path that gets added to the `PSModulePath` will be a we'll-known `Modules` folder. That exists in the FunctionApp directory.

If my FunctionApp exists at `C:\Temp\MyFuncApp` then the following path will be added to the beginning of the `PSModulePath`:

`C:\Temp\MyFuncApp\Modules`

In the beginning, we will have have the user do the `Save-Module` to that path. This makes the pack easier (#68). In the future, we should leverage the PSModulePath on their system and have `pack` pull these modules from there, to the `Modules` while deploying.

**Comment by eduardomourar** [comment]
I believe PSDepend and Powershell 6.1 should be part of the powershell azure functions docker image. Here is a way to work with the example PSCoreApp and install dependencies:
```dockerfile
# Install powershell project dependencies
FROM mcr.microsoft.com/powershell:6.1.0-debian-8 as builder

WORKDIR /tmp
COPY ./requirements.psd1 .
RUN pwsh -c "Install-Module -Name PSDepend -Scope CurrentUser -Force" \
    && pwsh -c "Set-Location . ; Invoke-PSDepend -Force"

FROM mcr.microsoft.com/azure-functions/powershell:2.0

WORKDIR $AzureWebJobsScriptRoot
COPY --from=builder /tmp/Modules/ /azure-functions-host/workers/powershell/Modules/
COPY . .
```

**Comment by TylerLeonhardt** [comment]
So this would be to have the container do the installing of the Modules and allow the user to specify them in the `requirements.psd1` rather than having to bundle their modules themselves?

**Comment by eduardomourar** [comment]
As you guys can see in the python and Nodejs docker image, at least one package management is available (pip and npm, respectively). They are not doing the dependencies installation as far as I know, but makes everything easy to start if you have them available.
If none of this makes sense, do put a dockerfile in the example folder so that even people without powershell installed in their local machine can try it out.
About not being opinionated, the moment you chose to have the worker and the example using PSDepend that went out the window, right? Not that I mind because I think PSDepend is quite useful and simple to use.

**Comment by JustinGrote** [comment]
A package manager is included, PowerShellGet and Package Management for
psgallery and nuget repositories, respectively.

The worker itself doesn't use PSDepend, just the build script. And the
example is just that, an example, the Readme explains multiple options for
handling dependencies. I think it could be more clear that it expects you
to bring PSDepend in either through your deoloyment package or via
save-module.

I just don't think it makes sense to include it in the image itself "by
default", however it's fully useful and functional and encouraged to use I
would agree because it's simple and easy, much like many other modules one
could argue should be "default" like PoshRsJob, PowershellYaml, etc.
